-- Run this in Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.matches (
  id bigint generated by default as identity primary key,
  submitted_by uuid not null references public.profiles(id) on delete cascade,
  player_a uuid not null references public.profiles(id) on delete cascade,
  player_b uuid not null references public.profiles(id) on delete cascade,
  player_a_games int not null check (player_a_games >= 0 and player_a_games <= 15),
  player_b_games int not null check (player_b_games >= 0 and player_b_games <= 15),
  status text not null default 'pending' check (status in ('pending', 'confirmed', 'rejected')),
  created_at timestamptz not null default now(),
  confirmed_at timestamptz,
  constraint different_players check (player_a <> player_b),
  constraint max_15_games check (player_a_games + player_b_games <= 15)
);

alter table public.profiles enable row level security;
alter table public.matches enable row level security;

create policy "Profiles are viewable by signed-in users" on public.profiles for select to authenticated using (true);
create policy "Users can insert own profile" on public.profiles for insert to authenticated with check (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

create policy "Matches are viewable by signed-in users" on public.matches for select to authenticated using (true);
create policy "Player can submit own match" on public.matches for insert to authenticated with check (auth.uid() = submitted_by and auth.uid() = player_a);
create policy "Opponent can confirm match" on public.matches for update to authenticated using (auth.uid() = player_b and status = 'pending') with check (auth.uid() = player_b and status in ('confirmed','rejected'));
